### ISSUE TITLE
Bug: custom fields fail to display and index when imported from another exhibit

### ISSUE THREAD

**Issue by corylown** [projectblacklight/spotlight#3199]
### Description
When an exhibit with custom fields is exported and then that exported file is imported to another exhibit all the custom field information is stored in `SolrDocumentSidecar` and the keys of the hash get transformed from strings (as they're stored in the original exhibit) to symbols (when imported to the new exhibit). Because we're not handling the possibility that these keys could be either strings or symbols, indexing breaks and the custom field metadata does not appear in the new exhibit.

### Steps to reproduce

1. Export an exhibit with custom metadata.
2. Create a new exhibit and import the exported file to this exhibit.
3. Observe that indexing fails and the custom metadata value does not appear in the edit form for items with values in that custom field.

Example of the indexing error from the Stanford Exhibits app:

<img width="791" alt="Screenshot 2024-10-16 at 9 56 03 AM" src="https://github.com/user-attachments/assets/402cc756-3266-4562-aa05-d7baf306fb72">

Comparing the sidecar data for an exhibit created by hand via the UI (`id: 9`) vs. an exhibit with imported custom fields (`id: 10`):

```
 #<Spotlight::SolrDocumentSidecar:0x000000010aba5c88
  id: 9,
  exhibit_id: 5,
  public: true,
  data: {"note"=>"this is a note"}, # <======== Here's the custom field
  created_at: "2024-10-16 06:47:11.953453000 -0700",
  updated_at: "2024-10-16 06:47:52.473365000 -0700",
  document_id: "bn910qm3619",
  document_type: "SolrDocument",
  resource_id: 8,
  resource_type: nil,
  index_status:
   {:ok=>true, :timestamp=>Wed, 16 Oct 2024 06:47:12.016384000 PDT -07:00},
  tag_list: nil>,
 #<Spotlight::SolrDocumentSidecar:0x000000010aba5788
  id: 10,
  exhibit_id: 6,
  public: true,
  data: {:note=>"this is a note"}, # <======== Here's the custom field
  created_at: "2024-10-16 06:47:11.953000000 -0700",
  updated_at: "2024-10-16 06:49:05.854385000 -0700",
  document_id: "bn910qm3619",
  document_type: "SolrDocument",
  resource_id: 9,
  resource_type: nil,
  index_status:
   {:ok=>true, :timestamp=>Wed, 16 Oct 2024 06:49:05.849455000 PDT -07:00},
  tag_list: nil>]
```

### Expected behavior

Spotlight should either always store imported hashes with string keys AND/OR it should be able to handle cases where the keys are either strings or symbols. Since it's likely data is stored with both string and symbol keys in production instances we'll probably need to be able to correctly handle either string or symbol keys in custom metadata

**Comment by dnoneill** [comment]
I will need a little time to dig, but right now this looks almost the exact same as what I was seeing in: https://github.com/projectblacklight/spotlight/pull/3197

**Comment by dnoneill** [comment]
@corylown, 99% sure this is solved with https://github.com/projectblacklight/spotlight/pull/3197

**Comment by corylown** [comment]
Verify if https://github.com/projectblacklight/spotlight/pull/3197 fixed the issue.

**Comment by ebtoner** [comment]
I tested this locally, and while I'm not seeing the reindexing error message originally reported, the custom field metadata fields are still not appearing in a newly imported exhibit. So this is still an issue. Putting this back into "To Do," since this might end up being a more complex problem.

**Comment by corylown** [comment]
At first glance the problem appears to be that the keys in the data attribute for the SolrDocumentSidecar are imported as symbols instead of strings. The fix is to convert the keys to strings before storing them in the database by adding a line to `exhibit_import_export_service.rb`:

```
      hash[:solr_document_sidecars].each do |attr|
        ar = exhibit.solr_document_sidecars.find_or_initialize_by(document_id: attr[:document_id])
        attr[:data] = attr[:data].clone.transform_keys(&:to_s) if attr[:data] # <= this is the fix
        ar.update(attr)
      end
```

But this is one of those bugs that gets worse the closer to you look at it. Export/import is also not correctly handling the relationships between Resource and SolrDocumentSidecar.

In the original exhibit (the one used to generate the export). The sidecar and resource data in the database looks like this:

```
=> 
[#<Spotlight::Resources::Upload:0x0000000137a3e020
  id: 1,
  exhibit_id: 1,
  type: "Spotlight::Resources::Upload",
  url: nil,
  data:
   {"full_title_tesim"=>"uploaded item title", "spotlight_upload_description_tesim"=>"uploaded item description", "spotlight_upload_attribution_tesim"=>"", "spotlight_upload_date_tesim"=>"", "custom-field"=>"uploaded item custom field"},
  indexed_at: nil,
  created_at: "2025-09-17 13:34:26.494332000 +0000",
  updated_at: "2025-09-17 13:34:26.494332000 +0000",
  metadata: nil,
  index_status: nil,
  upload_id: 1>]
  
  
[#<Spotlight::SolrDocumentSidecar:0x0000000144e329f8
  id: 1,
  exhibit_id: 1,
  public: true,
  data:
   {"custom-field"=>"uploaded item custom field", "configured_fields"=>{"full_title_tesim"=>"uploaded item title", "spotlight_upload_description_tesim"=>"uploaded item description"}},
  created_at: "2025-09-17 13:34:26.506915000 +0000",
  updated_at: "2025-09-17 13:34:26.649011000 +0000",
  document_id: "1-1",
  document_type: "SolrDocument",
  resource_id: 1,
  resource_type: nil,
  index_status: {},
  tag_list: nil>]
```

Setting aside for a moment that it seems odd that we're storing the same/similar data on Resource and SolrDocumentSidecar, the sidecar is at least correctly related to the resource by resource id.

Things get weird when you import this data into the second exhibit, where you end up with a new resource related to the new exhibit with the data values you'd expect from the original resource (but with symbol keys that probably also need fixing). But we also weirdly end up with two sidecars. One is from the import and has the custom field values in data but despite being related to the new exhibit it keeps its relationship to the resource in the original exhibit (hmmm...). The second sidecar is related to the new resource but is missing the data attributes that it should probably have from the imported sidecar. I _think_ what ought to happen is the new sidecar should be related to the new exhibit and the new resource, but have the data from the imported sidecar.

```
[#<Spotlight::Resources::Upload:0x0000000164151e08
  id: 2,
  exhibit_id: 2,
  type: "Spotlight::Resources::Upload",
  url: nil,
  data:
   {:full_title_tesim=>"uploaded item title", :spotlight_upload_description_tesim=>"uploaded item description", :spotlight_upload_attribution_tesim=>"", :spotlight_upload_date_tesim=>"", :"custom-field"=>"uploaded item custom field"},
  indexed_at: nil,
  created_at: "2025-09-17 13:34:26.494000000 +0000",
  updated_at: "2025-09-17 13:36:38.209299000 +0000",
  metadata: nil,
  index_status: nil,
  upload_id: 2>]
  
internal(dev)> Spotlight::Exhibit.find_by(slug: 'second').solr_document_sidecars
  Spotlight::Exhibit Load (0.2ms)  SELECT "spotlight_exhibits".* FROM "spotlight_exhibits" WHERE "spotlight_exhibits"."slug" = 'second' LIMIT 1 /*application='Internal'*/
  Spotlight::SolrDocumentSidecar Load (1.4ms)  SELECT "spotlight_solr_document_sidecars".* FROM "spotlight_solr_document_sidecars" WHERE "spotlight_solr_document_sidecars"."exhibit_id" = 2 /* loading for pp */ LIMIT 11 /*application='Internal'*/
=> 
[#<Spotlight::SolrDocumentSidecar:0x0000000164155508
  id: 2,
  exhibit_id: 2,
  public: true,
  data:
   {:"custom-field"=>"uploaded item custom field", :configured_fields=>{:full_title_tesim=>"uploaded item title", :spotlight_upload_description_tesim=>"uploaded item description"}},
  created_at: "2025-09-17 13:34:26.506000000 +0000",
  updated_at: "2025-09-17 13:34:26.649000000 +0000",
  document_id: "1-1",
  document_type: "SolrDocument",
  resource_id: 1,
  resource_type: nil,
  index_status: {},
  tag_list: nil>,
 #<Spotlight::SolrDocumentSidecar:0x00000001641553c8
  id: 3,
  exhibit_id: 2,
  public: true,
  data: {"configured_fields"=>{}},
  created_at: "2025-09-17 13:36:38.197853000 +0000",
  updated_at: "2025-09-17 13:36:38.324192000 +0000",
  document_id: "2-2",
  document_type: "SolrDocument",
  resource_id: 2,
  resource_type: nil,
  index_status: {},
  tag_list: nil>]
```
